### ISSUE TITLE
Update symengine.py to the latest version (V 0.10.0) and fix related bug

### ISSUE THREAD

**Issue by VahidGh** [CardiacModelling/model-reduction-manifold-boundaries#1]
When tried to reproduce the results described in the README file, got an error related to symengine version 0.7.0.
Tried to use the latest version of symengine.py (V 0.10.0), found out its Matrix function input mismatch with the old code and needs a review and update.

`python compute_geodesics_i5.py --done --plot`

```
Traceback (most recent call last):
  File "model-reduction-manifold-boundaries/MBAM/compute_geodesics_i5.py", line 76, in <module>
    funcs = GetSensitivityEquations(par, x, y, v, rates, A, B, ICs, para, second_order=second_order, conductance=conductance)
  File "model-reduction-manifold-boundaries/MBAM/lib/sensitivity_equations.py", line 33, in __init__
    self.compute_sensitivity_equations_rhs(x, y, v, rates, rhs, ICs, para, conductance)
  File "model-reduction-manifold-boundaries/MBAM/lib/sensitivity_equations.py", line 109, in compute_sensitivity_equations_rhs
    jS1 = [se.Matrix([fS1]).jacobian(se.Matrix([Ss]))]
File "symengine_wrapper.pyx", line 3278, in symengine.lib.symengine_wrapper.DenseMatrixBase.__cinit__
  File "symengine_wrapper.pyx", line 535, in symengine.lib.symengine_wrapper.sympify
  File "symengine_wrapper.pyx", line 537, in symengine.lib.symengine_wrapper.sympify
  File "symengine_wrapper.pyx", line 582, in symengine.lib.symengine_wrapper._sympify
  File "symengine_wrapper.pyx", line 503, in symengine.lib.symengine_wrapper.sympy2symengine
symengine.lib.symengine_wrapper.SympifyError: sympy2symengine: Cannot convert 'array([y0*(-exp(x0) - exp(x4) - exp(x3 + v*exp(x9))) + (exp(x1 - v*exp(x2)) - exp(x3 + v*exp(x9)))*y1 - exp(x3 + v*exp(x9))*y2 + exp(x3 + v*exp(x9)),
       (-exp(x1 - v*exp(x2)) - exp(x5 + v*exp(x6)))*y1 + exp(x0)*y0 + exp(x7 - v*exp(x8))*y2,
       exp(x5 + v*exp(x6))*y1 - exp(x7 - v*exp(x8))*y2,
       (exp(x1 - v*exp(x2)) - exp(x3 + v*exp(x9)))*dy1dx0 + (-exp(x0) - exp(x4) - exp(x3 + v*exp(x9)))*dy0dx0 - exp(x0)*y0 - exp(x3 + v*exp(x9))*dy2dx0,
       (-exp(x1 - v*exp(x2)) - exp(x5 + v*exp(x6)))*dy1dx0 + exp(x0)*dy0dx0 + exp(x0)*y0 + exp(x7 - v*exp(x8))*dy2dx0,
       exp(x5 + v*exp(x6))*dy1dx0 - exp(x7 - v*exp(x8))*dy2dx0,
       (exp(x1 - v*exp(x2)) - exp(x3 + v*exp(x9)))*dy1dx1 + (-exp(x0) - exp(x4) - exp(x3 + v*exp(x9)))*dy0dx1 + exp(x1 - v*exp(x2))*y1 - exp(x3 + v*exp(x9))*dy2dx1,
       (-exp(x1 - v*exp(x2)) - exp(x5 + v*exp(x6)))*dy1dx1 + exp(x0)*dy0dx1 - exp(x1 - v*exp(x2))*y1 + exp(x7 - v*exp(x8))*dy2dx1,
       exp(x5 + v*exp(x6))*dy1dx1 - exp(x7 - v*exp(x8))*dy2dx1,
       (exp(x1 - v*exp(x2)) - exp(x3 + v*exp(x9)))*dy1dx2 + (-exp(x0) - exp(x4) - exp(x3 + v*exp(x9)))*dy0dx2 - exp(x3 + v*exp(x9))*dy2dx2 - v*exp(x1 + x2 - v*exp(x2))*y1,
       (-exp(x1 - v*exp(x2)) - exp(x5 + v*exp(x6)))*dy1dx2 + exp(x0)*dy0dx2 + exp(x7 - v*exp(x8))*dy2dx2 + v*exp(x1 + x2 - v*exp(x2))*y1,
       exp(x5 + v*exp(x6))*dy1dx2 - exp(x7 - v*exp(x8))*dy2dx2,
       (exp(x1 - v*exp(x2)) - exp(x3 + v*exp(x9)))*dy1dx3 + (-exp(x0) - exp(x4) - exp(x3 + v*exp(x9)))*dy0dx3 - exp(x3 + v*exp(x9))*dy2dx3 - exp(x3 + v*exp(x9))*y0 - exp(x3 + v*exp(x9))*y1 - exp(x3 + v*exp(x9))*y2 + exp(x3 + v*exp(x9)),
       (-exp(x1 - v*exp(x2)) - exp(x5 + v*exp(x6)))*dy1dx3 + exp(x0)*dy0dx3 + exp(x7 - v*exp(x8))*dy2dx3,
       exp(x5 + v*exp(x6))*dy1dx3 - exp(x7 - v*exp(x8))*dy2dx3,
       (exp(x1 - v*exp(x2)) - exp(x3 + v*exp(x9)))*dy1dx4 + (-exp(x0) - exp(x4) - exp(x3 + v*exp(x9)))*dy0dx4 - exp(x4)*y0 - exp(x3 + v*exp(x9))*dy2dx4,
       (-exp(x1 - v*exp(x2)) - exp(x5 + v*exp(x6)))*dy1dx4 + exp(x0)*dy0dx4 + exp(x7 - v*exp(x8))*dy2dx4,
       exp(x5 + v*exp(x6))*dy1dx4 - exp(x7 - v*exp(x8))*dy2dx4,
       (exp(x1 - v*exp(x2)) - exp(x3 + v*exp(x9)))*dy1dx5 + (-exp(x0) - exp(x4) - exp(x3 + v*exp(x9)))*dy0dx5 - exp(x3 + v*exp(x9))*dy2dx5,
       (-exp(x1 - v*exp(x2)) - exp(x5 + v*exp(x6)))*dy1dx5 + exp(x0)*dy0dx5 - exp(x5 + v*exp(x6))*y1 + exp(x7 - v*exp(x8))*dy2dx5,
       exp(x5 + v*exp(x6))*dy1dx5 + exp(x5 + v*exp(x6))*y1 - exp(x7 - v*exp(x8))*dy2dx5,
       (exp(x1 - v*exp(x2)) - exp(x3 + v*exp(x9)))*dy1dx6 + (-exp(x0) - exp(x4) - exp(x3 + v*exp(x9)))*dy0dx6 - exp(x3 + v*exp(x9))*dy2dx6,
       (-exp(x1 - v*exp(x2)) - exp(x5 + v*exp(x6)))*dy1dx6 + exp(x0)*dy0dx6 + exp(x7 - v*exp(x8))*dy2dx6 - v*exp(x5 + x6 + v*exp(x6))*y1,
       exp(x5 + v*exp(x6))*dy1dx6 - exp(x7 - v*exp(x8))*dy2dx6 + v*exp(x5 + x6 + v*exp(x6))*y1,
       (exp(x1 - v*exp(x2)) - exp(x3 + v*exp(x9)))*dy1dx7 + (-exp(x0) - exp(x4) - exp(x3 + v*exp(x9)))*dy0dx7 - exp(x3 + v*exp(x9))*dy2dx7,
       (-exp(x1 - v*exp(x2)) - exp(x5 + v*exp(x6)))*dy1dx7 + exp(x0)*dy0dx7 + exp(x7 - v*exp(x8))*dy2dx7 + exp(x7 - v*exp(x8))*y2,
       exp(x5 + v*exp(x6))*dy1dx7 - exp(x7 - v*exp(x8))*dy2dx7 - exp(x7 - v*exp(x8))*y2,
       (exp(x1 - v*exp(x2)) - exp(x3 + v*exp(x9)))*dy1dx8 + (-exp(x0) - exp(x4) - exp(x3 + v*exp(x9)))*dy0dx8 - exp(x3 + v*exp(x9))*dy2dx8,
       (-exp(x1 - v*exp(x2)) - exp(x5 + v*exp(x6)))*dy1dx8 + exp(x0)*dy0dx8 + exp(x7 - v*exp(x8))*dy2dx8 - v*exp(x7 + x8 - v*exp(x8))*y2,
       exp(x5 + v*exp(x6))*dy1dx8 - exp(x7 - v*exp(x8))*dy2dx8 + v*exp(x7 + x8 - v*exp(x8))*y2,
       v*exp(x3 + x9 + v*exp(x9)) + (exp(x1 - v*exp(x2)) - exp(x3 + v*exp(x9)))*dy1dx9 + (-exp(x0) - exp(x4) - exp(x3 + v*exp(x9)))*dy0dx9 - exp(x3 + v*exp(x9))*dy2dx9 - v*exp(x3 + x9 + v*exp(x9))*y0 - v*exp(x3 + x9 + v*exp(x9))*y1 - v*exp(x3 + x9 + v*exp(x9))*y2,
       (-exp(x1 - v*exp(x2)) - exp(x5 + v*exp(x6)))*dy1dx9 + exp(x0)*dy0dx9 + exp(x7 - v*exp(x8))*dy2dx9,
       exp(x5 + v*exp(x6))*dy1dx9 - exp(x7 - v*exp(x8))*dy2dx9,
       (exp(x1 - v*exp(x2)) - exp(x3 + v*exp(x9)))*dy1dx10 + (-exp(x0) - exp(x4) - exp(x3 + v*exp(x9)))*dy0dx10 - exp(x3 + v*exp(x9))*dy2dx10,
       (-exp(x1 - v*exp(x2)) - exp(x5 + v*exp(x6)))*dy1dx10 + exp(x0)*dy0dx10 + exp(x7 - v*exp(x8))*dy2dx10,
       exp(x5 + v*exp(x6))*dy1dx10 - exp(x7 - v*exp(x8))*dy2dx10],
      dtype=object)' (of type <class 'numpy.ndarray'>) to a symengine type.
```

I fixed the issue for one of the occurrences. Please let me know if that's OK to update all similar ones using the same solution.

Suggested fix for: https://github.com/CardiacModelling/model-reduction-manifold-boundaries/blob/5f7fe3a4dfe0e242eb175a6299b2e4eafbcbcd6f/MBAM/lib/sensitivity_equations.py#L109
`jS1 = [se.Matrix(list(fS1)).jacobian(se.Matrix(list(Ss)))]`

**Comment by mirams** [comment]
What was the error related to symengine 0.7.0? As that's the pinned version in the requirements.txt

**Comment by VahidGh** [comment]
Was an installation issue. 
Installing on a MacBook (with Intel cpu) and Python 3.10.
